version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: techflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: techflow_erp
      MYSQL_USER: techflow_user
      MYSQL_PASSWORD: techflow123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - techflow-network

  adminer:
    image: adminer:latest
    container_name: techflow-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - techflow-network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  techflow-network:
    driver: bridge